import {Engine} from "./engine";
import {Report} from "./report";
import {Dealer} from "./dealer";
import {Fuel} from "./fuel";
import {Color} from "./color";
import {Make} from "./make";
import {Transmission} from "./transmission";
import {Trim} from "./trim";
import {Drivetrain} from "./drivetrain";
import {Image} from "./image";
import {Option} from "./option";
import {Body} from "./body";

export interface Auto {
  id: number;
  body: Body;
  cityMpg: number;
  description: string;
  engine: Engine;
  exteriorColor: string;
  fleet: boolean;
  report: Report;
  dealer?: Dealer;
  fuelTankVolume: string;
  fuel: Fuel;
  highwayMpg: number;
  horsepower: number;
  interiorColor: string;
  isCab: boolean;
  isCpo: boolean;
  isNew: boolean;
  isOemcpo: boolean;
  color: Color;
  listingId: string;
  mainPictureUrl: string;
  make: Make;
  seating: number;
  mileage: number;
  modelName: string;
  power: string;
  price: number;
  torque: string;
  transmission: Transmission;
  trim: Trim;
  drivetrain: Drivetrain;
  year: number;
  images: Image[];
  options: Option[];
}
